---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: example sg
      amazon.aws.ec2_security_group:
        name: "demo-sg"
        description: sg with rule descriptions
        vpc_id: "vpc-0927e8e29721bc9eb" 
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22