---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Route53 A type
      amazon.aws.route53:
      state: present
      zone: foo.com
      record: new.foo.com
      type: A
      ttl: 7200
      value: 1.1.1.1,2.2.2.2,3.3.3.3
      wait: true